#Docker Compose for develop
#star:  docker-compose -f docker-compose-scrap-api.yml up -d
#stop:  docker-compose -f docker-compose-scrap-api.yml rm -fsv
#  docker exec  -it endif-scrap-api-v1 sh -c "cd /usr/local/src; sh"
#   DEV : . scrap                     #Procesa solo la primera tarea pendiente
#   PROD:  python scrap_launch.py     #Se queda a la espera
#LOG: docker logs endif-scrap-api-v1

#Usar variables dentro de compose: https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution

version: '3.7'

services:
#Base de datos mongo 
  mongo:
    #docker run --rm --name endif-mongo-container -d -v $(pwd)/mongo-volume:/data/db -p 27017:27017 mongo:4.4
    image: 'mongo:4.4'
    container_name: 'endif-mongo-container'
    restart: always
    init: true
    #environment:
     #   - MONGO_INITDB_ROOT_DATABASE=db-endif
     #   - MONGO_INITDB_ROOT_USERNAME=root
     #   - MONGO_INITDB_ROOT_PASSWORD=7Vctnp_pju2
    ports:
      - "27017:27017"
    volumes:
     # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      #- ./mongo-volume:/data/db
      # Si  existe la variable de entorno carga FOLDER_DATABASE si no ./mongo-volume
      - ~/tmp/endif-mongo-volume:/data/db
 
    networks:
      - mongo-compose-network
     #command: mongod

#Scraper(demonio) + Fast API: 
# docker exec -it endif-scrap_launch
# cd /usr/local/src ;   python scrap_launch.py
  scrap_launch:
    image: "raulreyero/endif-scrap-api:v4"
    container_name: 'endif-scrap-api-v4'
    depends_on:
      - "mongo"
    restart: always
    volumes: 
      - ./workdir:/workdir
    # - ./src:/usr/local/src
    #  - ./requirements.txt:/tmp/requirements.txt
    shm_size: '2gb'
    env_file:
      - .env
    ports:
      - "5001:80"
    links:
      - "mongo:mongo"
    networks:
      - mongo-compose-network
    #PENDIENTE. Mejorarlo para que sea en base a la variable de entorno
    command: 
      /bin/sh -c ". init_all.sh ; sh"   
      
    stdin_open: true # docker run -i
    tty: true        # docker run -t
     


#Mongo Express: Visualizar los datos
  express:
    image: mongo-express
    container_name: 'endif-express'
    env_file:
      - .env
    depends_on:
      - "mongo"
    ports:
      - "5099:8081"
    links:
      - "mongo:mongo"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      #Se leen de variables de configuración en .env
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
    networks:
      - mongo-compose-network      

networks: 
    mongo-compose-network:
      driver: bridge
      name: mongo-compose-network
